In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
# converting into daterime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.Extract year

In [9]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## Extract month

In [11]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [12]:
date['date_month_no'] = date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

## Extract Days

In [13]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year date_month_no  date_day
0 2019-12-10        5628       25       3       2019      December        10
1 2018-08-15        3646       14     157       2018        August        15
2 2018-10-23        1859       25       1       2018       October        23
3 2019-08-17        7292       25       1       2019        August        17
4 2019-01-06        4344       25       3       2019       January         6

In [15]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,1,1
1,2018-08-15,3646,14,157,2018,August,2,2
2,2018-10-23,1859,25,1,2018,October,1,1
3,2019-08-17,7292,25,1,2019,August,5,5
4,2019-01-06,4344,25,3,2019,January,6,6

In [18]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019      December         1         1       Tuesday
1 2018-08-15       2018        August         2         2     Wednesday
2 2018-10-23       2018       October         1         1       Tuesday
3 2019-08-17       2019        August         5         5      Saturday
4 2019-01-06       2019       January         6         6        Sunday

In [20]:
# is weekend ?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,1,1,Tuesday,0
1,2018-08-15,2018,August,2,2,Wednesday,0
2,2018-10-23,2018,October,1,1,Tuesday,0
3,2019-08-17,2019,August,5,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

## Extract week of the year

In [23]:
date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,1,1,Tuesday,0,50
1,2018-08-15,2018,August,2,2,Wednesday,0,33
2,2018-10-23,2018,October,1,1,Tuesday,0,43
3,2019-08-17,2019,August,5,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

## Extract Quarter

In [25]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,1,1,Tuesday,0,4,4
1,2018-08-15,2018,August,2,2,Wednesday,0,3,3
2,2018-10-23,2018,October,1,1,Tuesday,0,4,4
3,2019-08-17,2019,August,5,5,Saturday,1,3,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

## Extract Semester

In [26]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,1,1,Tuesday,0,4,4,2
1,2018-08-15,2018,August,2,2,Wednesday,0,3,3,2
2,2018-10-23,2018,October,1,1,Tuesday,0,4,4,2
3,2019-08-17,2019,August,5,5,Saturday,1,3,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

## Extract time elapsed between dates

In [27]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 10, 18, 13, 23, 950492)

In [29]:
today - date['date']

0     2313 days 18:13:23.950492
1     2795 days 18:13:23.950492
2     2726 days 18:13:23.950492
3     2428 days 18:13:23.950492
4     2651 days 18:13:23.950492
                 ...
995   2741 days 18:13:23.950492
996   2682 days 18:13:23.950492
997   2530 days 18:13:23.950492
998   2595 days 18:13:23.950492
999   2369 days 18:13:23.950492
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# days passed
(today - date['date']).dt.days

0      2313
1      2795
2      2726
3      2428
4      2651
       ...
995    2741
996    2682
997    2530
998    2595
999    2369
Name: date, Length: 1000, dtype: int64

In [33]:
# month passed
date['months_passed'] = np.round((today - date['date']) / np.timedelta64(30, 'D'), 0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,2019,December,1,1,Tuesday,0,4,4,2,77.0
1,2018-08-15,2018,August,2,2,Wednesday,0,3,3,2,93.0
2,2018-10-23,2018,October,1,1,Tuesday,0,4,4,2,91.0
3,2019-08-17,2019,August,5,5,Saturday,1,3,3,2,81.0
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1,88.0

# Working with time

In [35]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [36]:
# converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [37]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [38]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract Time part

In [39]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time Difference

In [40]:
today - time['date']

0     4499 days 17:23:23.950492
1     4363 days 18:33:23.950492
2     4849 days 17:52:23.950492
3     4151 days 17:42:23.950492
4     4548 days 19:02:23.950492
                 ...
995   5138 days 17:23:23.950492
996   4459 days 18:59:23.950492
997   4924 days 18:36:23.950492
998   5040 days 18:39:23.950492
999   4312 days 18:48:23.950492
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
# in seconds
(today - time['date'])/np.timedelta64(1, 's')

0      3.887762e+08
1      3.770300e+08
2      4.190179e+08
3      3.587101e+08
4      3.930157e+08
           ...
995    4.439858e+08
996    3.853260e+08
997    4.255006e+08
998    4.355232e+08
999    3.726245e+08
Name: date, Length: 1000, dtype: float64

In [43]:
# in minutes
(today - time['date'])/np.timedelta64(1, 'm')

0      6.479603e+06
1      6.283833e+06
2      6.983632e+06
3      5.978502e+06
4      6.550262e+06
           ...
995    7.399763e+06
996    6.422099e+06
997    7.091676e+06
998    7.258719e+06
999    6.210408e+06
Name: date, Length: 1000, dtype: float64

In [44]:
# in hours
(today - time['date'])/np.timedelta64(1, 'h')

0      107993.389986
1      104730.556653
2      116393.873320
3       99641.706653
4      109171.039986
           ...
995    123329.389986
996    107034.989986
997    118194.606653
998    120978.656653
999    103506.806653
Name: date, Length: 1000, dtype: float64