1.Importing Pandas

In [6]:
import pandas as pd

2.opening a Local csv file

In [7]:
df=pd.read_csv('Fortune 500.csv')

In [8]:
df

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
496,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
497,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
498,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
499,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

Openning a csv file from url

In [ ]:
import request
from io import StringIO

url= "https://raw.githubusercontent.com/cs09/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0(Macintosh;Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = request.get(url,headers = headers)
data = StringIO(req.text)

pd.read_csv(data)

Sep parameter

In [15]:
pd.read_csv('Fortune 500.csv',sep='/t',names=['sno','name','release_year','rating','votes']) #converted csv file into tsv but "tsv" is converted in "csv" then use'/t'

/var/folders/ry/wgj587lj7y5fgymw0jbl6lgm0000gn/T/ipykernel_18195/2696268509.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv('Fortune 500.csv',sep='/t',names=['sno','name','release_year','rating','votes']) #converted csv file into tsv but "tsv" is converted in "csv" then use'/t'

,sno,name,release_year,rating,votes
0,"Rank,Company Name,Number of Employees,Previous...",NaN,NaN,NaN,NaN
1,"1,Walmart,""23,00,000"",1,""$4,85,873"",0.8%,""$13,...",NaN,NaN,NaN,NaN
2,"2,Berkshire Hathaway,""3,67,700"",4,""$2,23,604"",...",NaN,NaN,NaN,NaN
3,"3,Apple,""1,16,000"",3,""$2,15,639"",-7.7%,""$45,68...",NaN,NaN,NaN,NaN
4,"4,Exxon Mobil,""72,700"",2,""$2,05,004"",-16.7%,""$...",NaN,NaN,NaN,NaN
...,...,...,...,...,...
496,"496,Michaels Cos.,""31,000"",517,""$5,197"",5.8%,$...",NaN,NaN,NaN,NaN
497,"497,Toll Brothers,""4,200"",576,""$5,170"",23.9%,$...",NaN,NaN,NaN,NaN
498,"498,Yahoo,""8,500"",513,""$5,169"",4.0%,-$214.3,-,...",NaN,NaN,NaN,NaN
499,"499,Vistra Energy,""4,431"",,""$5,164"",-,-,-,""$15...",NaN,NaN,NaN,NaN
500,"500,ABM Industries,""1,10,000"",485,""$5,145"",-2....",NaN,NaN,NaN,NaN

5.Index_col Parameter

In [17]:
pd.read_csv('Fortune 500.csv',index_col='Rank')

,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Rank,,,,,,,,,
1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...
496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

6. Header Parameter

In [18]:
pd.read_csv('Fortune 500.csv',header=1)

,1,Walmart,"23,00,000",1.1,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
0,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
1,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
2,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
3,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
4,6,UnitedHealth Group,"2,30,000",6.0,"$1,84,840",17.7%,"$7,017.0",20.7%,"$1,22,810","$1,57,793"
...,...,...,...,...,...,...,...,...,...,...
494,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
495,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
496,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
497,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
498,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

7.use_cols Parameter

In [19]:
pd.read_csv('Fortune 500.csv',usecols=['Company Name','Revenues','Profits'])

           Company Name   Revenues    Profits
0               Walmart  $4,85,873  $13,643.0
1    Berkshire Hathaway  $2,23,604  $24,074.0
2                 Apple  $2,15,639  $45,687.0
3           Exxon Mobil  $2,05,004   $7,840.0
4              McKesson  $1,92,487   $2,258.0
..                  ...        ...        ...
495       Michaels Cos.     $5,197     $378.2
496       Toll Brothers     $5,170     $382.1
497               Yahoo     $5,169    -$214.3
498       Vistra Energy     $5,164          -
499      ABM Industries     $5,145      $57.2

[500 rows x 3 columns]

8.Squeeze parameter

In [20]:
pd.read_csv('Fortune 500.csv',usecols=['Company Name'],squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

9.skiprows/nrows Parameter

In [21]:
pd.read_csv('Fortune 500.csv',skiprows=[0,5])

,1,Walmart,"23,00,000",1.1,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
0,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
1,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
2,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
3,6,UnitedHealth Group,"2,30,000",6.0,"$1,84,840",17.7%,"$7,017.0",20.7%,"$1,22,810","$1,57,793"
4,7,CVS Health,"2,04,000",7.0,"$1,77,526",15.8%,"$5,317.0",1.5%,"$94,462","$81,310"
...,...,...,...,...,...,...,...,...,...,...
493,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
494,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
495,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
496,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
497,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

In [22]:
pd.read_csv('Fortune 500.csv',nrows=100)

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...,...
95,96,Charter Communications,"91,500",292.0,"$29,003",197.3%,"$3,522.0",-,"$1,49,067","$1,00,595"
96,97,Northwestern Mutual,"5,646",100.0,"$28,799",2.4%,$818.0,0.4%,"$2,50,441",-
97,98,Facebook,"17,048",157.0,"$27,638",54.2%,"$10,217.0",177.0%,"$64,961","$4,10,522"
98,99,Travelers Cos.,"30,900",105.0,"$27,625",3.1%,"$3,014.0",-12.4%,"$1,00,245","$33,689"
99,100,Capital One Financial,"47,300",112.0,"$27,519",9.6%,"$3,751.0",-7.4%,"$3,57,033","$41,831"

10.Encoding parameter

In [23]:
pd.read_csv('zomato.csv',encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

11. Skip Bad Line

In [ ]:
pd.read_csv('zomato.csv',error_bad_line=False)

12.dtype parameter

In [28]:
pd.read_csv('Fortune 500.csv',dtype={'Rank':float})

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1.0,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2.0,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3.0,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4.0,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5.0,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...,...
495,496.0,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
496,497.0,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
497,498.0,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
498,499.0,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
499,500.0,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

13.Handling dates

In [40]:
pd.read_csv('matches.csv',parse_dates=['date']).info

<bound method DataFrame.info of       id  season       city       date                        team1  \
0      1    2017  Hyderabad 2017-04-05          Sunrisers Hyderabad
1      2    2017       Pune 2017-04-06               Mumbai Indians
2      3    2017     Rajkot 2017-04-07                Gujarat Lions
3      4    2017     Indore 2017-04-08       Rising Pune Supergiant
4      5    2017  Bangalore 2017-04-08  Royal Challengers Bangalore
..   ...     ...        ...        ...                          ...
631  632    2016     Raipur 2016-05-22             Delhi Daredevils
632  633    2016  Bangalore 2016-05-24                Gujarat Lions
633  634    2016      Delhi 2016-05-25          Sunrisers Hyderabad
634  635    2016      Delhi 2016-05-27                Gujarat Lions
635  636    2016  Bangalore 2016-05-29          Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field
633        Kolkata Knight Riders        Kolkata Knight Riders         field
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
631  normal           0  Royal Challengers Bangalore            0
632  normal           0  Royal Challengers Bangalore            0
633  normal           0          Sunrisers Hyderabad           22
634  normal           0          Sunrisers Hyderabad            0
635  normal           0          Sunrisers Hyderabad            8

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
631               6         V Kohli
632               4  AB de Villiers
633               0    MC Henriques
634               4       DA Warner
635               0     BCJ Cutting

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar
1             Maharashtra Cricket Association Stadium   A Nand Kishore
2              Saurashtra Cricket Association Stadium      Nitin Menon
3                              Holkar Cricket Stadium     AK Chaudhary
4                               M Chinnaswamy Stadium              NaN
..                                                ...              ...
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore
632                             M Chinnaswamy Stadium     AK Chaudhary
633                                  Feroz Shah Kotla        M Erasmus
634                                  Feroz Shah Kotla        M Erasmus
635                             M Chinnaswamy Stadium  HDPK Dharmasena

             umpire2  umpire3
0           NJ Llong      NaN
1             S Ravi      NaN
2          CK Nandan      NaN
3      C Shamshuddin      NaN
4                NaN      NaN
..               ...      ...
631     BNJ Oxenford      NaN
632  HDPK Dharmasena      NaN
633    C Shamshuddin      NaN
634        CK Nandan      NaN
635     BNJ Oxenford      NaN

[636 rows x 18 columns]>

14.Converters

In [41]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else :
        return name

In [42]:
rename("Royal Challengers Bangalore")

'RCB'

In [44]:
pd.read_csv('matches.csv',converters={'team2':rename})

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,RCB,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,RCB,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,RCB,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,RCB,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

15.na_values Parameter

In [49]:
pd.read_csv('matches.csv',na_values=['umpire1'])

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

16.Loading a Huge dataset in chunks

In [50]:
dfs = pd.read_csv('matches.csv',chunksize=100)

In [52]:
for chunks in dfs:
    print(chunks.shape)

(100, 18)
(100, 18)
(100, 18)
(100, 18)
(100, 18)
(36, 18)